### ISSUE TITLE
Add steam, spotify, discord by default ?

### ISSUE THREAD

**Issue by DraGiuS** [dapperlinux/dapper-kickstarts#1]
Hello, i suggest to add these apps via flatpak, it would be good.

**Comment by matthewruffell** [comment]
Hi.
Steam, Spotify, Discord and VS Code are all proprietary software. 

For starters, proprietary software is not allowed to be redistributed by third parties, so I cannot distribute that software in Dapper Linux by law.

Secondly, I'm not a fan of proprietary software. I'm one of those people who believe in open source software, and in Stallman's four freedoms of open source software, so I'm not interested in using them anyway.

You are welcome to install them when you install Dapper Linux. Simply open up gnome-software and search for what you want and click install. It's pretty easy these days. Should only take you a minute. All the Flatpak repositories are added already.

I'm happy to include missing PaX flags if they are needed, and I ship correct PaX flags for Spotify already, since a few users like it.

And Gedit will stay, since that's my primary text editor. I do all my programming for Dapper Linux, Kernel patches for Dapper Secure Kernel Patchset, my PhD work and all the courses I teach / tutor at University in Gedit. I was never a fan of IDE's since they were always too clunky and never worked, while writing code in Gedit and compiling in a terminal worked wonderfully. I will look at moving to gnome-builder in the future though, since it has some nice features and its starting to get stable.

**Comment by DraGiuS** [comment]
Maybe you can add keepassx or audacity, at least ?

**Comment by matthewruffell** [comment]
I have been thinking about Audacity, also Blender, and Scribus too. Just got to decide if I want to make my .iso image any bigger, since people email me and say 3.7gb is too large already. 

I ship a large amount of software for a few reasons: 1) I like having a snapshot of software I can look back on in a few years time and think wow, that's what Linux was like back then. 2) Its great having common stuff work out of the box. 3) I can set PaX flags correctly and things "just work" without getting PaX mprotect errors. 4) The .iso is then very useful as a live system, so you don't need to install anything if you don't trust your internet connection.

BTW, you are welcome to make a custom Dapper Linux .iso with the applications you want in it. Just edit dapper-packages.ks file in this repo, and include the flatpaks you want installed, and then follow the instructions on the README to build an .iso image. You will need to do it in a Fedora 28 VM.

It's pretty straightforward. I try and keep this repo up to date so that Dapper Linux builds without problems so people can replicate my work.
